import numpy as np
from scipy import linalg
from matplotlib import pyplot as plt

from fatiando import mesher, gridder, utils

import scipy.special

def ellipsoid (xp,yp,zp,xc,yc,zc,a,b,azimuth,delta,declirem,inclirem,intensity,decT,incT,intT,k):
    '''
    Calculates the three componentes of magnetic field generated by an ellipsoid.
    
    input:
    xp,yp - Origin of the ellipsoid in the geographic coordinate.
    zp - Depth of the the ellipsoid.
    a,b - Minor and major axis, respectively.
    azimuth - angle in relation to the major-axe and the geographic north (0<=alpha<=360, radians).
    delta - Inclination between the major-axe and the horizontal plane (0<=delta<=90, radians).
    xc,yc,zc - point in the grid that has the center of the ellipsoid.
    declirem - declination of the remanent vector.
    inclirem - inclination of the remanent vector.
    intensity - intensity of the remanent vector.
    intT - Intensity of the Earth's magnetic field.
    incT - Inclination of the Earth's magnetic field.
    decT - Declination of the Earth's magnetic field.
    k - 3x3 matrix where each line has the intensity, declination and inclination of the three susceptibilities vectors.
    
    output:
    Bx, By, Bz, Tf - components of magnetic field generated by an ellipsoid and the total-field anomaly.
    '''
    
    center = np.array([xc,yc,zc])
    axis = np.array([a,b])
    
    azimuth = np.deg2rad(azimuth)
    delta = np.deg2rad(delta)
    angles = np.array([azimuth,delta,(np.pi/2)])
    
    mcon, mconT = m_convO(angles)
    
    declirem = np.deg2rad(declirem)
    inclirem = np.deg2rad(inclirem)
    
    ln,mn,nn = lmnn_v (declirem, inclirem)
    
    decT = np.deg2rad(decT)
    incT = np.deg2rad(incT)
    
    lt,mt,nt = lmnn_v (decT, incT)

    k_int = np.array([k[0][0],k[1][0],k[2][0]])
    k_inc = np.array([k[0][1],k[1][1],k[2][1]])
    k_dec = np.array([k[0][2],k[1][2],k[2][2]])
    
    if k_int[0] == (k_int[1] and k_int[2]):
        km = k_matrix(k_int,mcon)
    else:
        km = k_matrix2(k_int,mcon)

    # Earth's field and total body magnetization (including demagnetization) in the body's coordinate
    F = F_e (intT,lt,mt,nt,mcon)
    JN = JN_e (intensity,ln,mn,nn,mcon)
    N1,N2 = N_desmag (axis[0],axis[1])
    JR = JR_e (km,JN,F)
    JRD = JRD_e (km,N1,N2,JR)
    JRD_carte = (mconT).dot(JRD)
    JRD_ang = utils.vec2ang(JRD_carte)
    
    # Ellipsoid cartesian body coordinates
    x1,x2,x3 = x_e (xp,yp,zp,center,mcon)

    # Auxiliar calculations
    r = r_e (x1,x2,x3)
    delta = delta_e (r,axis[0],axis[1],x1,x2,x3)

    # Largest real root of the cubic equation (Lambda)
    lamb = lamb_e (r,axis[0],axis[1],delta)

    # Derivatives of lambda
    dlambx1,dlambx2,dlambx3 = dlambx_e (axis[0],axis[1],x1,x2,x3,lamb,r,delta)
    
    # Auxiliar calculations of the magnetic field
    f1 = f1_e (axis[0],axis[1],x1,x2,x3,lamb,JRD)
    arctang = arctang_O (axis[0],axis[1],lamb)
    f2 = f2_e (axis[0],axis[1],lamb,arctang)
    
    # Components of the magnetic field in the body coordinates
    B1 = B1_e (dlambx1,JRD,f1,f2,arctang,axis[0],axis[1],lamb)
    B2 = B2_e (dlambx2,JRD,f1,f2)
    B3 = B3_e (dlambx3,JRD,f1,f2)
    
    # Components of the magnetic field in the cartesian coordinates
    Bx = Bx_c (B1,B2,B3,mcon[0,0],mcon[1,0],mcon[2,0])
    By = By_c (B1,B2,B3,mcon[0,1],mcon[1,1],mcon[2,1])
    Bz = Bz_c (B1,B2,B3,mcon[0,2],mcon[1,2],mcon[2,2])
    
    Tf = (Bx*np.cos(incT)*np.cos(decT) + By*np.cos(incT)*np.sin(decT) + Bz*np.sin(incT))
    
    return Bx, By, Bz, Tf
    
def m_convO (angles):
    '''
    Builds the matrix of coordinate system change to the center of the ellipsoid. Used for the oblate ellipsoid.
        
    input:
    alpha - Azimuth in relation to the major-axe and the geographic north (0<=alpha<=360, radians).
    delta - Inclination between the major-axe and the horizontal plane (0<=delta<=90, radians).
    gamma - Angle between the intermediate-axe and the vertical projection of the horizontal plane to the
    center of the ellipsoid.
        
    output:
    A 3x3 matrix.
    '''
    
    mcon = np.zeros((3,3))
    mcon[0][0] = (np.cos(angles[0])*np.sin(angles[1]))
    mcon[1][0] = (-np.cos(angles[0])*np.cos(angles[1]))
    mcon[2][0] = (-np.sin(angles[0]))
    mcon[0][1] = (np.sin(angles[0])*np.sin(angles[1]))
    mcon[1][1] = (-np.sin(angles[0])*np.cos(angles[1]))
    mcon[2][1] = (np.cos(angles[0]))
    mcon[0][2] = (-np.cos(angles[1]))
    mcon[1][2] = (-np.sin(angles[1]))
    mcon[2][2] = (0.)
    mconT = (mcon).T
    return mcon, mconT
    
def lmnn_v (dec, inc):

    '''
    Calculates de direction cosines of a vector.
    
    input:
    inc - Inclination.
    dec - Declination.
    
    output:
    ln,mn,nn - direction cosines.    
    '''
    
    ln = (np.cos(dec)*np.cos(inc))
    mn = (np.sin(dec)*np.cos(inc))
    nn = np.sin(inc)
    return ln, mn, nn
    
def F_e (intT,lt,mt,nt,mcon):
    '''
    Change the magnetization vetor of the Earth's field to the body coordinates.
    
    input:
    inten - Intensity of the Earth's magnetic field.
    lt,mt,nt - direction cosines of the Earth's magnetic field.
    l1,l2,l3,m1,m2,m3,n1,n2,n3 - matrix of body coordinates change.
    
    output:
    Ft - The magnetization vetor of the Earth's field to the body coordinates.    
    '''
    F = intT*np.array([[(lt*mcon[0,0]+mt*mcon[0,1]+nt*mcon[0,2])], [(lt*mcon[1,0]+mt*mcon[1,1]+nt*mcon[1,2])], [(lt*mcon[2,0]+mt*mcon[2,1]+nt*mcon[2,2])]])
    return F
    
def JN_e (intensity,ln,mn,nn,mcon):
    '''
    Changes the remanent magnetization vector to the body coordinate.
        
    input:
    intensity - intensity of remanent vector.
    ln,nn,mn - direction cosines of the remanent magnetization vector.
    mcon - matrix of conversion.
        
    output:
    JN - Remanent magnetization vector in the body coordinate.         
    '''
    JN = intensity*np.array([[(ln*mcon[0,0]+mn*mcon[0,1]+nn*mcon[0,2])], [(ln*mcon[1,0]+mn*mcon[1,1]+nn*mcon[1,2])], [(ln*mcon[2,0]+mn*mcon[2,1]+nn*mcon[2,2])]])
    return JN

def N_desmag (a,b):
    '''
    Calculates the three demagnetization factor along major, intermediate and minor axis. For the oblate ellipsoid use.
        
    input:
    a,b - Major and minor axis, respectively.
      
    output:
    N1, N2 - Major and minor demagnetization factors, respectively.        
    '''
    N1 = ((4.*np.pi*a*b**2)/((b**2-a**2)**1.5)) * ((((b**2-a**2)**0.5)/(a)) - np.arctan(((b**2-a**2)**0.5)/(a)))
    N2 = 2.*np.pi - N1/2.
    return N1, N2
    
def k_matrix (k_int,mcon):
    '''
    Build susceptibility tensors matrix for the isotropic case in the body coordinates.
        
    input:
    mcon - Matrix of conversion.
    k_int - Intensity of the three directions of susceptibility.
        
    output:
    km - Susceptibility tensors matrix.        
    '''
        
    km = np.zeros([3,3])
    for i in range (3):
        for j in range (3):
            for r in range (3):
                km[i,j] = km[i,j] + (k_int[r]*(mcon[r,0]*mcon[i,0] + mcon[r,1]*mcon[i,1] + mcon[r,2]*mcon[i,2])*(mcon[r,0]*mcon[j,0] + mcon[r,1]*mcon[j,1] + mcon[r,2]*mcon[j,2]))
    return km

def k_matrix2 (k_int,mcon):
    '''
    Build the susceptibility tensors matrix for the anisotropic case in the body coordinates.
        
    input:
    mcon - Matrix of conversion.
    k_int - Intensity of the three directions of susceptibility.
        
    output:
    km - Susceptibility tensors matrix.        
    '''
        
    Lr = np.zeros(3)
    Mr = np.zeros(3)
    Nr = np.zeros(3)
    for i in range (3):
        Lr[i] = np.cos(k_dec[i])*np.cos(k_inc[i])
        Mr[i] = np.sin(k_dec[i])*np.cos(k_inc[i])
        Nr[i] = np.sin(k_inc[i])
    km = np.zeros([3,3])
    for i in range (3):
        for j in range (3):
            for r in range (3):
                km[i,j] = km[i,j] + (k_int[r]*(Lr[r]*mcon[i,0] + Mr[r]*mcon[i,1] + Nr[r]*mcon[i,2])*(Lr[r]*mcon[j,0] + Mr[r]*mcon[j,1] + Nr[r]*mcon[j,2]))
    return km
    
def JR_e (km,JN,F):
    '''
    Calculates the resultant magnetization vector without self-demagnetization correction.
    
    input:
    km - matrix of susceptibilities tensor.
    JN - Remanent magnetization
    Ft - Magnetization vetor of the Earth's field in the body coordinates.
    
    output:
    JR - Resultant magnetization vector without self-demagnetization correction.   
    '''
    
    JR = km.dot(F) + JN
    return JR
    
def JRD_e (km,N1,N2,JR):
    '''
    Calculates resultant magnetization vector with self-demagnetization correction.
    
    input:
    km - matrix of susceptibilities tensor.
    N1,N2,N3 - Demagnetization factors in relation to a, b and c, respectively.
    JR - resultant magnetization vector without self-demagnetization correction.
    
    output:
    JRD - Resultant magnetization vector without self-demagnetization correction.    
    '''
    
    I = np.identity(3)
    kn0 = km[:,0]*N1
    kn1 = km[:,1]*N2
    kn2 = km[:,2]*N2
    kn = (np.vstack((kn0,kn1,kn2))).T
    A = I + kn
    JRD = (linalg.inv(A)).dot(JR)
    return JRD
    
def x_e (xp,yp,zp,center,mcon):
    '''
    Calculates the new coordinates with origin at the center of the ellipsoid.

    input:
    xp,yp - Origin of the ellipsoid in the geographic coordinate.
    zp - Depth of the the ellipsoid.
    mcon - Matrix of conversion.
        
    output:
    x1, x2, x3 - The three axes of the coordinates.
    '''
    
    x1 = (xp-center[0])*mcon[0,0]+(yp-center[1])*mcon[0,1]-(zp+center[2])*mcon[0,2]
    x2 = (xp-center[0])*mcon[1,0]+(yp-center[1])*mcon[1,1]-(zp+center[2])*mcon[1,2]
    x3 = (xp-center[0])*mcon[2,0]+(yp-center[1])*mcon[2,1]-(zp+center[2])*mcon[2,2]
    return x1, x2, x3

def r_e (x1,x2,x3):
    '''
    Calculates the distance between the observation point and the center of the ellipsoid.
    Used in the oblate and oblate ellipsoids.
      
    input:
    x1, x2, x3 - Axis of the body coordinate system.
      
    output:
    r - Distance between the observation point and the center of the ellipsoid.        
    '''
    
    r = ((x1)**2+(x2)**2+(x3)**2)**0.5
    return r
    
def delta_e (r,a,b,x1,x2,x3):
    '''
    Calculates an auxiliar constant for lambda.
        
    input:
    a, b, c - Major, intermediate and minor axis, respectively.
    r - Distance between the observation point and the center of the ellipsoid.
    x1, x2, x3 - Axis of the body coordinate system.
       
    output:
    delta - Auxiliar constant for lambda.        
    '''

    delta = (r**4 + (a**2-b**2)**2 - 2*(a**2-b**2) * (x1**2 - x2**2 - x3**2))**0.5
    return delta    
    
def lamb_e (r,a,b,delta):
    '''
    Calculates the Larger root of the cartesian ellipsoidal equation.
    Used in the oblate ellipsoids.
      
    input:
    a, b, c - Major, intermediate and minor axis, respectively.
    delta - Auxiliar constant for lambda.
    r - Distance between the observation point and the center of the ellipsoid.
     
    output:
    lamb - Larger root of the cartesian ellipsoidal equation.
    '''
    lamb = (r**2 - a**2 - b**2 + delta)/2.
    return lamb

def dlambx_e (a,b,x1,x2,x3,lamb,r,delta):
    '''
    Calculates the derivatives of the ellipsoid equation for each body coordinates in realation to lambda.
    Used for the oblate ellipsoids.
    
    input:
    a, b, c - Major, intermediate and minor axis, respectively.
    x1, x2, x3 - Axis of the body coordinate system.
    delta - Auxiliar constant for lambda.
    
    output:
    dlambx1,dlambx2,dlambx3 - Derivatives of the ellipsoid equation for each body coordinates in realation to x1,x2 and x3.        
    '''
        
    dlambx1 = x1*(1+(r**2-a**2+b**2)/delta)
    dlambx2 = x2*(1+(r**2+a**2-b**2)/delta)
    dlambx3 = x3*(1+(r**2+a**2-b**2)/delta)
    return dlambx1, dlambx2, dlambx3

def f1_e (a,b,x1,x2,x3,lamb,JRD):
    '''
    Auxiliar calculus of magnetic field generated by a oblate ellipsoid.

    input:
    a,b - Major and minor axis, respectively.
    x1,x2,x3 - Axis of the body coordinate system.
    lamb - Larger root of the cartesian ellipsoidal equation.
    JRD - Resultant magnetization vector with self-demagnetization correction.
    
    output:
    f1 - Auxiliar calculus of magnetic field generated by a oblate or an oblate ellipsoid.
    '''
    
    f1 = 2*np.pi*a*(b**2)*(((JRD[0]*x1)/(((a**2+lamb)**1.5)*(b**2+lamb))) + ((JRD[1]*x2 + JRD[2]*x3)/(((a**2+lamb)**0.5)*((b**2+lamb)**2))))
    return f1
    
def arctang_O (a,b,lamb):
    '''
    Calculo auxiliar do campo magnetico (fi) com relacao aos eixos do ellipsoide 
    input:
    a,b - semi-eixos do ellipsoide
    lamb - Maior raiz real da equacao cubica.
    output:
    cte - constante escalar.
    '''
    arctang = np.arctan(((b**2-a**2)/(a**2+lamb))**0.5)
    return arctang
    
def f2_e (a,b,lamb,arctang):
    '''
    Auxiliar calculus of magnetic field generated by a oblate ellipsoid.

    input:
    a,b - Major and minor axis, respectively.
    lamb - Larger root of the cartesian ellipsoidal equation.
    log - Auxiliar calculus of magnetic field generated by a oblate ellipsoid.
    
    output:
    f2 - Auxiliar calculus of magnetic field generated by a oblate ellipsoid.
    '''
    
    f2 = ((2*np.pi*a*b*b)/((b*b-a*a)**1.5))*(((((b*b-a*a)*(a*a+lamb))**0.5)/(b*b+lamb)) - arctang)
    return f2

def B1_e (dlambx1,JRD,f1,f2,arctang,a,b,lamb):
    '''
    Calculates the B1 component of the magnetic field generated by n-ellipsoids in the body coordinates.
    Used in the oblate ellipsoid.
    
    input:
    dlambx1 - Derivative of the ellipsoid equation for each body coordinates in realation to x1.
    JRD - Resultant magnetization vector with self-demagnetization correction.
    f1,f2,arctang - Auxiliar calculus of magnetic field generated by a prolate ellipsoid.
    a,b - Major and minor axis, respectively.
    lamb - Larger root of the cartesian ellipsoidal equation.
    
    output:
    B1 - The B1 component of the magnetic field generated by n-ellipsoids in the body coordinates.
    '''
    
    B1 = (dlambx1*f1) + ((4*np.pi*a*b**2)/((b**2-a**2)**1.5)) * JRD[0] * (arctang - ((b**2-a**2)/(a**2+lamb))**0.5)
    return B1

def B2_e (dlambx2,JRD,f1,f2):
    '''
    Calculates the B2 component of the magnetic field generated by n-ellipsoids in the body coordinates.
    Used in the oblate ellipsoid.
    
    input:
    dlambx2 - Derivative of the ellipsoid equation for each body coordinates in realation to x2.
    JRD - Resultant magnetization vector with self-demagnetization correction.
    f1,f2 - Auxiliar calculus of magnetic field generated by a oblate ellipsoid.
    
    output:
    B2 - The B2 component of the magnetic field generated by n-ellipsoids in the body coordinates.
    '''
    
    B2 = (dlambx2*f1) + (JRD[1]*f2)
    return B2
    
def B3_e (dlambx3,JRD,f1,f2):
    '''
    Calculates the B3 component of the magnetic field generated by n-ellipsoids in the body coordinates.
    Used in the oblate ellipsoids.
    
    input:
    dlambx3 - Derivative of the ellipsoid equation for each body coordinates in realation to x3.
    JRD - Resultant magnetization vector with self-demagnetization correction.
    f1,f2 - Auxiliar calculus of magnetic field generated by a oblate ellipsoid.
    
    output:
    B3 - The B3 component of the magnetic field generated by n-ellipsoids in the body coordinates.
    '''
    
    B3 = (dlambx3*f1) + (JRD[2]*f2)
    return B3
    
def Bx_c (B1,B2,B3,l1,l2,l3):
    '''
    Change the X component of the magnetic field generated by n-ellipsoids to the cartesian coordinates.
    
    input:
    B1,B2,B3 - Components of the magnetic field generated by n-ellipsoids to the body coordinates.
    l1,l2,l3 - Direction cosines for coordinates change.
    
    output:
    Bz - The X component of the magnetic field generated by n-ellipsoids to the cartesian coordinates.
    '''
    
    Bx = B1*l1+B2*l2+B3*l3
    return Bx

def By_c (B1,B2,B3,m1,m2,m3):
    '''
    Change the Y component of the magnetic field generated by n-ellipsoids to the cartesian coordinates.
    
    input:
    B1,B2,B3 - Components of the magnetic field generated by n-ellipsoids to the body coordinates.
    m1,m2,m3 - Direction cosines for coordinates change.
    
    output:
    Bz - The Y component of the magnetic field generated by n-ellipsoids to the cartesian coordinates.
    '''
    
    By = B1*m1+B2*m2+B3*m3
    return By
    
def Bz_c (B1,B2,B3,n1,n2,n3):
    '''
    Change the Z component of the magnetic field generated by n-ellipsoids to the cartesian coordinates.
    
    input:
    B1,B2,B3 - Components of the magnetic field generated by n-ellipsoids to the body coordinates.
    n1,n2,n3 - Direction cosines for coordinates change.
    
    output:
    Bz - The Z component of the magnetic field generated by n-ellipsoids to the cartesian coordinates.
    '''
    
    Bz = B1*n1+B2*n2+B3*n3
    return Bz